import { useApp } from "../lib/store";
import { ageOf, fmtDate, fullName } from "../lib/data";
import type { Prescription } from "../lib/data";
import { Btn } from "./ui";
import { I } from "./icons";

/* Builds a standalone, print-ready HTML prescription letter. */
function letterHTML(hospital: string, rx: Prescription, patientName: string, patientMeta: string, patientCode: string,
  doctorName: string, doctorSpec: string, license: string, allergies: string[],
  rows: { name: string; generic: string; dosage: string; frequency: string; duration: string; qty: number }[], notes: string) {
  const date = fmtDate(rx.createdAt.slice(0, 10));
  const itemRows = rows.map((r, i) => `
    <tr>
      <td style="padding:8px 10px;border-bottom:1px solid #e2e8e4;font-weight:600;color:#14231e">${i + 1}. ${r.name}<div style="font-weight:400;font-size:11px;color:#7f918a">${r.generic}</div></td>
      <td style="padding:8px 10px;border-bottom:1px solid #e2e8e4;color:#48605a">${r.dosage}</td>
      <td style="padding:8px 10px;border-bottom:1px solid #e2e8e4;color:#48605a">${r.frequency}</td>
      <td style="padding:8px 10px;border-bottom:1px solid #e2e8e4;color:#48605a">${r.duration}</td>
      <td style="padding:8px 10px;border-bottom:1px solid #e2e8e4;color:#14231e;font-family:monospace;text-align:right">${r.qty}</td>
    </tr>`).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><title>${rx.code} — ${patientName}</title></head>
<body style="margin:0;background:#eef2ef;font-family:'Segoe UI',Arial,sans-serif;padding:32px 16px">
<div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #d8e1db;border-radius:8px;overflow:hidden">
  <div style="background:#0a2a21;color:#fff;padding:18px 28px;display:flex;justify-content:space-between;align-items:center">
    <div>
      <div style="font-size:19px;font-weight:800;letter-spacing:.2px">${hospital}</div>
      <div style="font-size:11px;color:#9fd8bf;margin-top:2px">Main Campus · Harbor District · +91 80 4711 0100</div>
    </div>
    <div style="font-family:Georgia,serif;font-size:34px;color:#3ED598;font-style:italic">℞</div>
  </div>
  <div style="padding:22px 28px">
    <div style="display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;border-bottom:2px solid #0a2a21;padding-bottom:14px">
      <div style="font-size:13px"><span style="color:#7f918a">Patient</span><br><strong style="font-size:16px">${patientName}</strong><br><span style="color:#48605a">${patientMeta} · ${patientCode}</span></div>
      <div style="font-size:13px;text-align:right"><span style="color:#7f918a">Prescribed by</span><br><strong>${doctorName}</strong><br><span style="color:#48605a">${doctorSpec} · Reg. ${license}</span></div>
      <div style="font-size:13px"><span style="color:#7f918a">Date</span><br><strong>${date}</strong><br><span style="color:#48605a;font-family:monospace">${rx.code}</span></div>
    </div>
    ${allergies.length ? `<div style="margin-top:14px;background:#faece6;border:1px solid #f0c8ba;color:#a03a24;font-size:12.5px;font-weight:700;padding:8px 12px;border-radius:6px">⚠ KNOWN ALLERGIES: ${allergies.map((a) => a.toUpperCase()).join(", ")}</div>` : ""}
    <table style="width:100%;border-collapse:collapse;margin-top:16px;font-size:13px">
      <thead><tr style="background:#ecf6f0;color:#0b6b51;font-size:10.5px;letter-spacing:1px;text-transform:uppercase;text-align:left">
        <th style="padding:8px 10px">Medicine</th><th style="padding:8px 10px">Dosage</th><th style="padding:8px 10px">Frequency</th><th style="padding:8px 10px">Duration</th><th style="padding:8px 10px;text-align:right">Qty</th>
      </tr></thead>
      <tbody>${itemRows}</tbody>
    </table>
    ${notes ? `<div style="margin-top:16px;background:#f4f7f5;border-left:3px solid #0e8262;padding:10px 14px;font-size:12.5px;color:#48605a"><strong>Doctor's notes:</strong> ${notes}</div>` : ""}
    <div style="margin-top:34px;display:flex;justify-content:space-between;align-items:flex-end">
      <div style="font-size:11px;color:#7f918a;max-width:320px">Take medicines after food unless advised otherwise. Report any rash, swelling or breathing difficulty immediately.</div>
      <div style="text-align:center"><div style="width:190px;border-top:1.5px solid #14231e;padding-top:6px;font-size:12.5px;font-weight:700">${doctorName}</div><div style="font-size:10.5px;color:#7f918a">Digital signature · verified</div></div>
    </div>
  </div>
  <div style="background:#f4f7f5;padding:10px 28px;font-size:10.5px;color:#7f918a;display:flex;justify-content:space-between">
    <span>Generated by Aurelia HMS · e-Prescription</span><span>This letter is valid for dispensing at any registered pharmacy.</span>
  </div>
</div>
</body></html>`;
}

export function RxLetterModal({ rx, onClose }: { rx: Prescription; onClose: () => void }) {
  const { s, toast } = useApp();
  const patient = s.patients.find((p) => p.id === rx.patientId);
  const doctor = s.doctors.find((d) => d.id === rx.doctorId);
  const rows = rx.items.map((it) => {
    const m = s.medicines.find((x) => x.id === it.medicineId);
    return { name: m?.name ?? "—", generic: m?.generic ?? "", dosage: it.dosage, frequency: it.frequency, duration: it.duration, qty: it.qty };
  });
  const patientName = patient ? fullName(patient) : "Patient";
  const patientMeta = patient ? `${ageOf(patient.dob)} yrs · ${patient.gender}` : "—";
  const doctorName = doctor?.name ?? "Duty Medical Officer";
  const allergies = patient?.allergies ?? [];

  const html = () =>
    letterHTML(s.hospitalName, rx, patientName, patientMeta, patient?.code ?? "—", doctorName, doctor?.specialization ?? "—",
      doctor?.license ?? "—", allergies, rows, rx.notes);

  const download = () => {
    const blob = new Blob([html()], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${rx.code}-${patientName.replace(/\s+/g, "-")}-prescription.html`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    window.setTimeout(() => URL.revokeObjectURL(url), 2000);
    toast("success", "Prescription letter downloaded", `${rx.code} saved — hand it to the patient.`);
  };

  const share = async () => {
    const text = `${s.hospitalName} — e-Prescription ${rx.code}\nPatient: ${patientName} (${patient?.code ?? ""})\nDoctor: ${doctorName}\n${rows.map((r, i) => `${i + 1}. ${r.name} — ${r.dosage}, ${r.frequency} × ${r.duration} (Qty ${r.qty})`).join("\n")}${rx.notes ? `\nNotes: ${rx.notes}` : ""}${allergies.length ? `\n⚠ Allergies: ${allergies.join(", ")}` : ""}`;
    try {
      if (navigator.share) {
        await navigator.share({ title: `${rx.code} — ${patientName}`, text });
        toast("success", "Prescription shared", "Sent through your device share sheet.");
        return;
      }
      throw new Error("no-share");
    } catch {
      try {
        await navigator.clipboard.writeText(text);
        toast("success", "Prescription copied", "Full letter text is on your clipboard — paste it in WhatsApp, SMS or email.");
      } catch {
        toast("error", "Sharing unavailable", "Use Download instead and send the file.");
      }
    }
  };

  const print = () => {
    const w = window.open("", "_blank", "width=820,height=900");
    if (!w) { toast("error", "Pop-up blocked", "Allow pop-ups to print, or use Download."); return; }
    w.document.write(html());
    w.document.close();
    w.focus();
    window.setTimeout(() => w.print(), 350);
    toast("info", "Sent to printer", "Choose “Save as PDF” in the dialog for a digital copy.");
  };

  return (
    <div className="fixed inset-0 z-50 grid place-items-center p-3 sm:p-4">
      <div className="absolute inset-0 bg-pine-950/60 backdrop-blur-[2px]" onClick={onClose} />
      <div className="pop-in relative bg-paper rounded-xl border border-line shadow-2xl w-full max-w-[680px] max-h-[92vh] flex flex-col overflow-hidden">
        <header className="flex items-center justify-between px-4 sm:px-5 py-3 border-b border-line bg-card shrink-0">
          <div>
            <h3 className="font-display font-extrabold text-[16px] text-ink leading-tight">Prescription letter · {rx.code}</h3>
            <p className="text-[11px] text-ink-faint">Preview exactly what the patient receives</p>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-md text-ink-faint hover:text-danger-600 hover:bg-danger-50 transition-colors" aria-label="Close">
            <I name="x" className="w-4 h-4" />
          </button>
        </header>

        <div className="overflow-y-auto scroll-slim p-3 sm:p-5">
          {/* the paper */}
          <div className="rx-print-area bg-white border border-line rounded-lg overflow-hidden shadow-[0_10px_30px_rgba(6,32,26,0.12)]">
            <div className="bg-pine-950 pine-tex px-5 sm:px-7 py-4 flex items-center justify-between text-white">
              <div>
                <p className="font-display font-extrabold text-[17px] leading-tight">{s.hospitalName}</p>
                <p className="text-[10.5px] text-brand-200/70 mt-0.5">Main Campus · Harbor District · +91 80 4711 0100</p>
              </div>
              <span className="font-display italic text-[38px] text-brand-400 leading-none select-none">℞</span>
            </div>

            <div className="px-5 sm:px-7 py-5">
              <div className="flex flex-wrap justify-between gap-x-6 gap-y-3 border-b-2 border-pine-950 pb-3.5 text-[12.5px]">
                <div>
                  <p className="micro text-ink-faint">Patient</p>
                  <p className="font-display font-bold text-[15px] text-ink mt-0.5">{patientName}</p>
                  <p className="text-ink-soft">{patientMeta} · <span className="font-mono text-[11px]">{patient?.code}</span></p>
                </div>
                <div className="sm:text-right">
                  <p className="micro text-ink-faint">Prescribed by</p>
                  <p className="font-semibold text-ink mt-0.5">{doctorName}</p>
                  <p className="text-ink-soft">{doctor?.specialization} · Reg. {doctor?.license}</p>
                </div>
                <div>
                  <p className="micro text-ink-faint">Date</p>
                  <p className="font-semibold text-ink mt-0.5">{fmtDate(rx.createdAt.slice(0, 10))}</p>
                  <p className="font-mono text-[11px] text-ink-soft">{rx.code}</p>
                </div>
              </div>

              {allergies.length > 0 && (
                <p className="mt-3.5 bg-danger-50 border border-danger-600/25 text-danger-700 text-[12px] font-bold px-3 py-2 rounded-md flex items-center gap-2">
                  <I name="alert" className="w-3.5 h-3.5 shrink-0" /> KNOWN ALLERGIES: {allergies.map((a) => a.toUpperCase()).join(", ")}
                </p>
              )}

              <table className="w-full mt-4 text-[12.5px]">
                <thead>
                  <tr className="micro text-brand-700 text-left bg-brand-50">
                    <th className="px-2.5 py-2 font-medium rounded-l-md">Medicine</th>
                    <th className="px-2.5 py-2 font-medium">Dosage</th>
                    <th className="px-2.5 py-2 font-medium">Frequency</th>
                    <th className="px-2.5 py-2 font-medium">Duration</th>
                    <th className="px-2.5 py-2 font-medium text-right rounded-r-md">Qty</th>
                  </tr>
                </thead>
                <tbody>
                  {rows.map((r, i) => (
                    <tr key={i} className="border-b border-line-soft last:border-0">
                      <td className="px-2.5 py-2.5 font-semibold text-ink">{i + 1}. {r.name}<span className="block text-[10px] font-normal text-ink-faint font-mono">{r.generic}</span></td>
                      <td className="px-2.5 py-2.5 text-ink-soft">{r.dosage}</td>
                      <td className="px-2.5 py-2.5 text-ink-soft">{r.frequency}</td>
                      <td className="px-2.5 py-2.5 text-ink-soft">{r.duration}</td>
                      <td className="px-2.5 py-2.5 text-right font-mono font-semibold text-ink">{r.qty}</td>
                    </tr>
                  ))}
                </tbody>
              </table>

              {rx.notes && (
                <p className="mt-4 bg-paper border-l-[3px] border-brand-600 px-3.5 py-2.5 text-[12px] text-ink-soft">
                  <span className="font-bold text-ink">Doctor's notes:</span> {rx.notes}
                </p>
              )}

              <div className="mt-9 flex items-end justify-between gap-6">
                <p className="text-[10.5px] text-ink-faint max-w-[290px] leading-relaxed">
                  Take medicines after food unless advised otherwise. Report any rash, swelling or breathing difficulty immediately.
                </p>
                <div className="text-center shrink-0">
                  <div className="w-[180px] border-t-[1.5px] border-ink pt-1.5 text-[12px] font-bold text-ink">{doctorName}</div>
                  <p className="micro text-ink-faint mt-0.5">Digital signature · verified</p>
                </div>
              </div>
            </div>

            <div className="bg-paper border-t border-line px-5 sm:px-7 py-2.5 flex flex-wrap justify-between gap-2 text-[10px] text-ink-faint">
              <span>Generated by Aurelia HMS · e-Prescription</span>
              <span>Valid for dispensing at any registered pharmacy</span>
            </div>
          </div>
        </div>

        <footer className="px-4 sm:px-5 py-3 border-t border-line bg-card flex flex-wrap justify-end gap-2 shrink-0">
          <Btn variant="outline" icon="share" onClick={share}>Share</Btn>
          <Btn variant="outline" icon="printer" onClick={print}>Print / PDF</Btn>
          <Btn icon="download" onClick={download}>Download letter</Btn>
        </footer>
      </div>
    </div>
  );
}
